### PR TITLE
Unique model names

### PR DESCRIPTION
**Pull request by azubieta**
This is an unfulfilled attempt of making model names unique.  Here you will find my progress so far.

Generating the unique names was the simple part. I got stuck trying to use those names in the relational fields.  I fear that it would take more complex changes to get this done.

Hints are welcome.

### CODE REVIEW

**Comment by rvalyi** [comment]
Hello @azubieta well, actually looking at other Brazilian fiscal documents than the invoice I have seen I have the same use case too so I promise I'll fix it. As far as I saw you did quite a great job collecting the unique names, I looked a bit how to use these names in the generation and it doesn't seem too hard for me to fix it. I'll let you know, hopefully in a week or so.

**Comment by azubieta** [comment]
Thanks @rvalyi, sorry to not finish it, I just got lost between Jinja and xsdata filters. It's my first time working with them. Please let me know if you need something else from me to added to this PR.

**Comment by rvalyi** [comment]
@azubieta I'll re-organize a bit the different bits and the commits, but I just wanted to let you know that basically I have it, so no need for you to try more. I'll try to push it till tomorrow. Thanks again, you did the hard part.

**Comment by azubieta** [comment]
@rvalyi sure no problem, thanks a lot for the help. By the way would it be possible for us to have a chat I may still have a wrong idea of how to use the whole thing. You can find mi as @azubieta in telegram too.

**Comment by rvalyi** [comment]
> @rvalyi sure no problem, thanks a lot for the help. By the way would it be possible for us to have a chat I may still have a wrong idea of how to use the whole thing. You can find mi as @azubieta in telegram too.

Hello, sorry I'm a bit late to do the push. I'll add you on Telegram, we can talk sure. In any case, I suggest you start by just overriding your generated abstract model with simple hand written code without using spec_driven_model. You can just override the relational fields from the abstract models to adjust the comodel to the proper concrete models where the mixins are injhected via _inherit. You probably don't need the StackedModel either. Then you can start by doing the serialization/deserialization with your xsdata pure Python binding lib with hand written code. I mean that would be an easy way to start without having to adopt a more opiniated module like spec_driven_model. But if you do that at least you would preserve the ability for your Odoo models to map to the XML automatically and you could adapt the way you do it later, possibly using spec_driven_model. Hopefully I'll be more available later in the week.

**Comment by rvalyi** [comment]
Hello @azubieta

you can find what seems a working version here https://github.com/akretion/xsdata-odoo/tree/naive-no-duplicate-ak
I made a single big commit for now, but I pretend to split it in smaller bits and include your commits.

But at least you can test if you want.

BTW this is crazy, I just updated our electronic invoicing schemas for Brazil and for the 1st time in more than 15 years we also do have duplicate tag names under different parents... (https://github.com/akretion/nfelib/pull/68)
So we will already benefit from your help here, even for the electronic invoicing...

**Comment by rvalyi** [comment]
Here you'll find the new PR https://github.com/akretion/xsdata-odoo/pull/8
it's including your work on generator.py which was mostly correct but I didn't include the other files as I didn't use the changes.

Thank you again for the hard work! Let me know if it fits your generation better.

**Comment by azubieta** [comment]
@rvalyi we found out that we don't need to have a copy of every single field or structure of our xml files, at least not for the invoice documents. Therefore we will not use the full generated models there. But we may use it in other documents which don't have a simile in Odoo.

I will close this PR, it's nice to help :)

**Comment by rvalyi** [comment]
hello @azubieta , it's important to understand that if in the mapping module where you inject the generated mixins into Odoo classes you override the fields and define they are *related* to other existing Odoo fields ou *computed*, then of course no extra column will be created in the database.

In fact, this is the case with 80% of the electronic invoicing fields we use most of the time in Brazil for instance. But I think even in this case it might still be interesting to have the generated models because then you can all the mappings very declarative and the import/export logic all automatic without having to code every matching logic in the import process for instance.

**Pull request closed without merging**
